### PR TITLE
do not use getchildren, removed in python 3.9

### PR DESCRIPTION
**Pull request by mwhudson**

### CODE REVIEW

**Review by jpfeuffer — APPROVED** [review]
Thanks a lot!

**Comment by jpfeuffer** [comment]
Is this finished from your side?

**Comment by mwhudson** [comment]
Yes. I didn't find any other calls to getchildren and the tests the Debian package runs pass now, I don't know how comprehensive they are though!

**Comment by mr-c** [comment]
FYI, the Debian package just runs[1] the `example.py` that comes from this repo (and is in the source tarball).

If there are other tests we can/should run, please let us know!

[1] Though we convert example.py to Python3 using `2to3` first

**Comment by jpfeuffer** [comment]
I think example.py is currently all we have, so this is fine for now. Although of course, more tests are desirable.

**Pull request merged**
