### PR TITLE
Switch to github actions

### LINKED ISSUE #26: Publish to PyPI

### PR DESCRIPTION
**Pull request by bernt-matthias**
copied the deploy action from https://github.com/hexylena/galaxyxml/blob/main/.github/workflows/deploy.yml

if you prefer to use a pypi API token we can change according to https://github.com/pypa/gh-action-pypi-publish

fixes: https://github.com/WorkflowConversion/CTDopts/issues/26

### CODE REVIEW

**Review by mr-c — APPROVED** [review]

**Comment by bernt-matthias** [comment]
Thanks for the approval. Not sure how the setup has to be done for deployment. 

Anyway, once merged I would move on to https://github.com/WorkflowConversion/CTDopts/issues/22 which should be easy as well. So maybe we can check the deployment afterwards....

**Comment by jpfeuffer** [comment]
Sounds good. We can merge and once you have something to release, we can tag the repo and the deployment job will start from there. And we will see if it works. Only one thing to consider: Do you want to release on every tag? I often prefix release tags but maybe on such a small project, it is easier your way.

**Comment by jpfeuffer** [comment]
You have merge permission, right? Please merge when you think it's done.

**Comment by bernt-matthias** [comment]
> You have merge permission, right?

Seems not to be the case.

**Pull request merged**
